### ISSUE TITLE
能后台下载不

### ISSUE THREAD

**Issue by alsojin0806** [Insfgg99x/FGGDownloader#1]
现在已经更新了后台下载支持

**Comment by Insfgg99x** [comment]
可以，需要配置下后台模式http://www.jianshu.com/p/4cc5dfcf4c6b

**Comment by alsojin0806** [comment]
锁屏 之后就停止下载 ,还有 按了 home 之后 ,间隔时间比较长的话 ,会提示失败 超时..
![eb7e5cdf812f28299c2210d17624bbf6](https://cloud.githubusercontent.com/assets/3974508/12470879/22817afc-c033-11e5-947c-bf05740c2df6.jpg)

**Comment by Insfgg99x** [comment]
开个后台任务

**Comment by alsojin0806** [comment]
利用NSURLSession进行background transfer task

backgroundSessionConfiguration 
跟你这个框架的请求方式 不是一样的把 ? 不知道你这个开启后台任务啥意思 ?

http://www.starming.com/index.php?v=index&view=69

**Comment by Insfgg99x** [comment]
你好，新增了后台下载和任务队列，现在磨人支持后台下载了
