### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by ghost** [Insfgg99x/FGGDownloader#11]
我使用此源码下载youtube的视频,速度隔好几秒才几百K 然后 如果我暂停再开始 他速度立马飙升到2MB/S(确定是真实速度) 持续好几秒后 又降下来了,然后暂停再开始 又飙升 再降0.0见鬼了顺便问下 NSURLconnection好旧了 为啥不用NSURLSession呢

**Comment by Insfgg99x** [comment]
这个速度不是真实下载速度，是采样速度，就是根据指定时间间隔内文件体积增加的大小来计算的下载网速，不是真实的网速

**Comment by Insfgg99x** [comment]
这个很久没更新了，用NSURLSession是一样的
