### ISSUE TITLE
下载取到了文件大小但是不下载

### ISSUE THREAD

**Issue by lxcsjk** [Insfgg99x/FGGDownloader#3]
-(void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data

只走一次

但是并没有下载完

**Comment by Insfgg99x** [comment]
不会吧，我之前介入过几次项目中，都是好的啊

**Comment by Insfgg99x** [comment]
你是不是把它的代理置空了

**Comment by lxcsjk** [comment]
我们公司网络出问题了。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
