### ISSUE TITLE
移除的方法里边有bug 当其他任务在下载的时候 移除会导致其他任务的按钮都变成恢复

### ISSUE THREAD

**Issue by taozi6206** [Insfgg99x/FGGDownloader#4]
//这个移除的方法里边有bug 当其他任务在下载的时候 移除会导致无法暂停
    [[FGGDownloadManager shredManager] removeForUrl:model.url file:model.destinationPath];
移除的时候下载队列出问题了

**Comment by taozi6206** [comment]
我帮你解决了
你设置一个全局变量 然后修改以下代码就可以了
 //这里应当在第一次运行的时候才会执行
    if (self.flag) return;
    if(_progressView.progress==1.0)
    {
        self.flag = YES;
        [_downloadBtn setTitle:@"完成" forState:UIControlStateNormal];
        _downloadBtn.enabled=NO;
    }
    else if(_progressView.progress>0.0)
    {
        self.flag = YES;
        [_downloadBtn setTitle:@"恢复" forState:UIControlStateNormal];
    }
    else
    {
        self.flag = YES;
        [_downloadBtn setTitle:@"开始" forState:UIControlStateNormal];
    }

**Comment by Insfgg99x** [comment]
cell复用的问题，这个支持无UI后台下载

**Comment by Insfgg99x** [comment]
这是demo UI刷新的一个问题，我已经修复了。
就是ViewController的commitEditing方法里的部分。
另外导致这个问题的原因是，cell的下载按钮的状态没有做细化的判断，只做了一个简单的判断，没有判断是否正在下载，若是正在下载，应该显示“暂停”，否则显示“恢复”，由于cell里没有做判断，所有统一显示成了“恢复”。在TaskCell里我有备注说明。
这并不影响下载本身。
