### ISSUE TITLE
能增加上传的demo吗

### ISSUE THREAD

**Issue by LCSomeSSSS** [Insfgg99x/FGGDownloader#7]
上传功能最好能增加一个demo，让新手学习下，谢谢！

**Comment by Insfgg99x** [comment]
加了，版本2.2已更新。
![image](https://user-images.githubusercontent.com/12442442/42011413-e02304c8-7ac5-11e8-9475-075ba81a1f97.png)

**Comment by LCSomeSSSS** [comment]
感谢！
